### PR TITLE
Fix tester

### LINKED ISSUE #14: Tests failing
https://github.com/NodeFactoryIo/dappeteer/pull/12/checks?check_run_id=1903669097

```
  dappeteer
Starting ganache...
Ganache running at http://localhost:8545
Starting test server...
Server running at http://localhost:8080
Deploying test contract...
web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
Contract deployed at 0x0fC7E4bD0784Af9b444015557CDBdA05d9D4D46e
    ✓ should be deployed, contract
    ✓ should running, puppeteer
    ✓ should open, metamask
    ✓ should open, test page
    ✓ should switch network, localhost (87ms)
    ✓ should import private key (382ms)
    ✓ should switch accounts (133ms)
    ✓ should lock and unlock (368ms)
    ✓ should connect to ethereum (1760ms)
    ✓ should be able to sign (958ms)
    1) should change gas values
    test contract
      2) should confirm transaction
      3) should have increased count


  10 passing (1m)
  3 failing

  1) dappeteer
       should change gas values:
     TimeoutError: waiting for selector `#txSent` failed: timeout 30000ms exceeded
      at new WaitTask (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)
      at DOMWorld.waitForSelectorInPage (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:416:26)
      at Object.internalHandler.waitFor (node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
      at DOMWorld.waitForSelector (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:312:29)
      at Frame.waitForSelector (node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:842:51)
      at Page.waitForSelector (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1285:33)
      at /home/runner/work/dappeteer/dappeteer/test/test.spec.ts:134:22
      at Generator.next (<anonymous>)
      at fulfilled (test/test.spec.ts:24:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) dappeteer
       test contract
         should confirm transaction:
     TimeoutError: waiting for selector `.btn-primary` failed: timeout 30000ms exceeded
      at new WaitTask (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)
      at DOMWorld.waitForSelectorInPage (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:416:26)
      at Object.internalHandler.waitFor (node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
      at DOMWorld.waitForSelector (node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:312:29)
      at Frame.waitForSelector (node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:842:51)
      at Page.waitForSelector (node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1285:33)
      at Object.<anonymous> (src/index.ts:153:58)
      at Generator.next (<anonymous>)
      at fulfilled (src/index.ts:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  3) dappeteer
       test contract
         should have increased count:

      AssertionError [ERR_ASSERTION]: Counter does not match BEFORE: 0 AFTER: 0
      + expected - actual

      -0
      +1
      
      at /home/runner/work/dappeteer/dappeteer/test/test.spec.ts:126:20
      at Generator.next (<anonymous>)
      at fulfilled (test/test.spec.ts:24:58)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

### PR DESCRIPTION
**Pull request by BeroBurny**
closes #14

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -199,7 +199,7 @@ export async function getMetamask(
       }
       await metamaskPage.reload()
 
-      const button = await metamaskPage.waitForSelector('.request-signature__footer__sign-button')
+      const button = await metamaskPage.waitForSelector('.button:nth-child(2)')
```
Comment (mpetrunic) [inline src/index.ts:202]:
```suggestion
      const button = await metamaskPage.waitForSelector('.signature-request-footer button:last-child')
```
race with old selector since new selector isn't backwards compatible

**Review by mpetrunic — CHANGES_REQUESTED** [review]

**Review by mpetrunic — APPROVED** [review]
